DECISION_TIER_ADOPT = "adopt"
DECISION_TIER_REVISE_ADOPT = "revise_adopt"
DECISION_TIER_REJECT = "reject"
DECISION_TIER_NEEDS_REVIEW = "needs_review"

STATUS_PUBLISHED = "published"
STATUS_REJECTED = "rejected"
STATUS_PENDING = "pending"

DECISION_TIER_OPTIONS = (
    (DECISION_TIER_ADOPT, "採用"),
    (DECISION_TIER_REVISE_ADOPT, "修正して採用"),
    (DECISION_TIER_REJECT, "不採用"),
    (DECISION_TIER_NEEDS_REVIEW, "要確認"),
)

DECISION_TIER_LABELS = {value: label for value, label in DECISION_TIER_OPTIONS}

DECISION_TIER_DESCRIPTIONS = {
    DECISION_TIER_ADOPT: "AI候補をそのまま信頼できる情報として保存します。",
    DECISION_TIER_REVISE_ADOPT: "AI候補をもとに、人が修正したテキストを保存します。",
    DECISION_TIER_REJECT: "候補を採用しません。理由も保存し、次回生成の調整に使います。",
    DECISION_TIER_NEEDS_REVIEW: "事実確認など、後で人が見直す必要がある場合に使います。",
}

TIER_TO_STATUS = {
    DECISION_TIER_ADOPT: STATUS_PUBLISHED,
    DECISION_TIER_REVISE_ADOPT: STATUS_PUBLISHED,
    DECISION_TIER_REJECT: STATUS_REJECTED,
    DECISION_TIER_NEEDS_REVIEW: STATUS_PENDING,
}
